padre(espanol,meztizo).
padre(indio,meztizo).
padre(espanol,castizo).
padre(mestizo ,castizo).
padre(espanol,espanol).
padre(castizo,espanol).  
padre(indio,zambo). 
padre(negro,zambo). 
padre(zambo,zambo_prieto).
padre(negro,zambo_prieto). 
padre(español,mulato).
padre(negro,mulato).
padre(mulato,morisco).
padre(español,morisco).
padre(español,albino). 
padre(morisco,albino).
padre(albino,salta_atrás).
padre(español,salta_atrás).
padre(mestizo,apinonado). 
padre(mulato,apinonado).
padre(indio,cholo).
padre(mestizo,cholo).
padre(mulato,chino).
padre(indio,chino).
padre(español,harnizo).
padre(cholo,harnizo).
padre(castizo,harnizo).
padre(mestizo,harnizo).
padre(coyote,chamizo).
padre(indio,chamizo).
padre(chino,cambujo).
padre(indio,cambujo).
padre(salta_atrás,lobo). 
padre(mulato,lobo).
padre(lobo,gíbaro).
padre(china,gíbaro). 
padre(gíbaro,albarazado).
padre(mulata,albarazado).
padre(albarazado,cambujo). 
padre(negra,cambujo).
padre(cambujo,sambaigo). 
padre(indio,sambaigo).
padre(sambaigo,campamulato).
padre(loba,campamulato).
padre(campamulato,tente_en_el_aire).
padre(cambuja,tente_en_el_aire).

meztizo(X,Z):-padre(X,meztizo),padre(Z,meztizo).
castizo(X,Z):-padre(X,castizo),padre(Z,castizo).
espanol(X,Z):-padre(X,espanol),padre(Z,espanol).
zambo(X,Z):-padre(X,zambo),padre(Z,zambo).
zambo_prieto(X,Z):-padre(X,zambo_prieto),padre(Z,zambo_prieto).
mulato(X,Z):-padre(X,mulato),padre(Z,mulato).
morisco(X,Z):-padre(X,morisco),padre(Z,morisco).
albino(X,Z):-padre(X,albino),padre(Z,albino).
salta_atrás(X,Z):-padre(X,salta_atrás),padre(Z,salta_atrás).
apinonado(X,Z):-padre(X,apinonado),padre(Z,apinonado).
cholo(X,Z):-padre(X,cholo),padre(Z,cholo).
chino(X,Z):-padre(X,chino),padre(Z,chino).
harnizo(X,Z):-padre(X,harnizo),padre(Z,harnizo).
chamizo(X,Z):-padre(X,chamizo),padre(Z,chamizo).
cambujo(X,Z):-padre(X,cambujo),padre(Z,cambujo).
lobo(X,Z):-padre(X,lobo),padre(Z,lobo).
gíbaro(X,Z):-padre(X,gíbaro),padre(Z,gíbaro).
albarazado(X,Z):-padre(X,albarazado),padre(Z,albarazado).
cambujo(X,Z):-padre(X,cambujo),padre(Z,cambujo).
sambaigo(X,Z):-padre(X,sambaigo),padre(Z,sambaigo).
campamulato(X,Z):-padre(X,campamulato),padre(Z,campamulato).
tente_en_el_aire(X,Z):-padre(X,tente_en_el_aire),padre(Z,tente_en_el_aire).
padre(X,Y).  
ancestro(X,Y):-padre(X,Z),padre(Z,Y).
